name: Christian Kallias - Author Site
favicon: null
layout_spectrum: 0.05785475834272802
typography_spectrum: 0.07614310435019433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3471646092366427
  lightness: 0.5427037707995623
  saturation: 0.7459370624274015
  rhythmicContrast: 0.4553473931737244
purpose: []
